### ISSUE TITLE
Non-decimal numbers

### ISSUE THREAD

**Issue by Johnymalina** [alex3305/lovelace-number-icons#1]
Hi,
i need icon to show just the number i enter without .0 in the end. Iam making automation for washing maschine that should have icons for 40, 60 etc degrees and the decimal point is pointless in this case. Is it possible to do it?

**Comment by alex3305** [comment]
Hi @Johnymalina 👋,

Thanks for opening this issue. You can use the `num:`-prefix to get numbers without decimals:
![image](https://github.com/user-attachments/assets/09718ea7-7bb2-4afd-b165-3ec5206705bd)

But I guess you want both? So numbers without a decimal point and with a degrees sign?

**Comment by Johnymalina** [comment]
Thanks for a quick reaction. Yes exactly. I was mainly interested if it would possible.

**Comment by alex3305** [comment]
I've just released version 1.3.0 with these types of icons added. You can use the `ndg:` prefix to use these icons.

Thanks for the input 🚀. I'm going to close this issue.

**Comment by Johnymalina** [comment]
Thanks a lot. I can confirm that its working.
